import { DEAL_STAGE_LABEL, DEAL_STAGE_ORDER } from "./constants";
import type { DealCard } from "./types";

export { DEAL_STAGE_LABEL, DEAL_STAGE_ORDER };

export const INITIAL_DEALS: DealCard[] = [
  {
    id: "deal-001",
    title: "就業規則の見直し相談",
    clientName: "株式会社青葉ロジ",
    contactName: "総務部 佐伯様",
    inquiryChannel: "紹介",
    referrer: "顧問税理士紹介",
    practiceArea: "労務",
    assignee: "高橋弁護士",
    stage: "intake",
    nextAction: "相談概要を確認して初回面談候補日を返す",
    nextActionDate: "2026-04-03",
    lastContactAt: "2026-04-01",
    estimatedValueLabel: "月額顧問 5万〜10万円想定",
    conflictCheckStatus: "未着手",
    summary:
      "既存の就業規則が現状に合っておらず、改訂範囲の見極めから相談したい。",
    note: "事前に現行就業規則と雇用区分一覧の共有を依頼。",
  },
  {
    id: "deal-002",
    title: "相続手続きの初回面談",
    clientName: "個人相談（相続）",
    contactName: "仮名: 田島様",
    inquiryChannel: "Web",
    referrer: "Web問い合わせ",
    practiceArea: "相続",
    assignee: "林弁護士",
    stage: "first_meeting",
    nextAction: "家族関係図と財産一覧のたたき台を送ってもらう",
    nextActionDate: "2026-04-06",
    lastContactAt: "2026-04-02",
    estimatedValueLabel: "初回相談後に見積提示",
    conflictCheckStatus: "確認中",
    summary:
      "遺産分割の方向性整理と、今後の手続きの流れを知りたい相談。",
    note: "次回面談で争点整理と必要資料の優先度を確認予定。",
  },
  {
    id: "deal-003",
    title: "顧問契約前の利益相反確認",
    clientName: "ミナト不動産管理株式会社",
    contactName: "代表 近藤様",
    inquiryChannel: "紹介",
    referrer: "既存顧客紹介",
    practiceArea: "企業法務",
    assignee: "中村弁護士",
    stage: "conflict_check",
    nextAction: "関連当事者名簿を受領し利益相反を最終確認",
    nextActionDate: "2026-04-02",
    lastContactAt: "2026-03-31",
    estimatedValueLabel: "月額顧問 8万円前後",
    conflictCheckStatus: "確認中",
    summary:
      "継続顧問前提で、利益相反と案件範囲のすり合わせを進めている。",
    note: "確認が終われば委任契約案へ進める想定。",
  },
  {
    id: "deal-004",
    title: "利用規約改定と委任契約案",
    clientName: "合同会社スカイウェブ",
    contactName: "事業責任者 森様",
    inquiryChannel: "電話",
    referrer: "既存問い合わせ再相談",
    practiceArea: "IT・企業法務",
    assignee: "高橋弁護士",
    stage: "proposal",
    nextAction: "見積と委任契約案の差分を説明する",
    nextActionDate: "2026-03-30",
    lastContactAt: "2026-03-28",
    estimatedValueLabel: "スポット 20万〜35万円想定",
    conflictCheckStatus: "問題なし",
    summary:
      "SaaS利用規約改定に伴うリスク整理と委任契約条件の確認段階。",
    note: "期限超過サンプル。先方確認待ちだが再連絡が必要。",
  },
  {
    id: "deal-005",
    title: "労務トラブルの受任見込",
    clientName: "株式会社南雲製作所",
    contactName: "管理部 小林様",
    inquiryChannel: "紹介",
    referrer: "社労士連携",
    practiceArea: "労務",
    assignee: "林弁護士",
    stage: "retainer_likely",
    nextAction: "受任条件を最終確認して委任契約締結へ進める",
    nextActionDate: "2026-04-04",
    lastContactAt: "2026-04-01",
    estimatedValueLabel: "着手金 30万円前後",
    conflictCheckStatus: "問題なし",
    summary:
      "面談と資料確認を終え、受任可否の最終判断と条件確認の段階。",
    note: "代表への報告用に進捗を見せたい案件。",
  },
  {
    id: "deal-006",
    title: "定期顧問の受任済みフォロー",
    clientName: "一般社団法人ひかり支援会",
    contactName: "事務局 長谷川様",
    inquiryChannel: "紹介",
    referrer: "司法書士連携",
    practiceArea: "顧問契約",
    assignee: "中村弁護士",
    stage: "retained",
    nextAction: "初回キックオフ日程を確定して議題案を送る",
    nextActionDate: "2026-04-07",
    lastContactAt: "2026-04-01",
    estimatedValueLabel: "月額顧問 12万円前後",
    conflictCheckStatus: "問題なし",
    summary: "委任契約締結済み。運用開始に向けてキックオフ調整中。",
    note: "受任済みとして色分け表示するサンプル案件。",
  },
  {
    id: "deal-007",
    title: "許認可支援の相談",
    clientName: "合同会社リバー開発",
    contactName: "代表 佐藤様",
    inquiryChannel: "Web",
    referrer: "既存顧客（不動産）",
    practiceArea: "許認可",
    assignee: "高橋弁護士",
    stage: "closed_lost",
    nextAction: "見送り理由を社内メモへ残す",
    nextActionDate: "2026-03-20",
    lastContactAt: "2026-03-20",
    estimatedValueLabel: "見送り",
    conflictCheckStatus: "未着手",
    summary: "予算都合で今期は見送り。来期に再相談の可能性あり。",
    note: "見送り理由と再接触時期だけ記録して保留。",
  },
  {
    id: "deal-008",
    title: "顧問先の定期面談フォロー",
    clientName: "有限会社テックサンプル",
    contactName: "管理部 山本様",
    inquiryChannel: "メール",
    referrer: "既存顧問先",
    practiceArea: "顧問契約",
    assignee: "中村弁護士",
    stage: "proposal",
    nextAction: "先方コメントを反映した議事メモを再送する",
    nextActionDate: "2026-04-08",
    lastContactAt: "2026-04-01",
    estimatedValueLabel: "追加支援 10万〜15万円想定",
    conflictCheckStatus: "問題なし",
    summary:
      "追加支援範囲のすり合わせ中。定期面談後のフォロー案件。",
    note: "今週フォロー一覧に出したいサンプル案件。",
  },
];
